# Generated by Django 4.0.1 on 2022-01-25 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_princi_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('marks', models.FloatField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'student',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intake', models.IntegerField(default=60)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.college')),
            ],
            options={
                'db_table': 'dept',
            },
        ),
    ]
